.github/workflows/build.yml

name: Build mod jar
on: [push, workflow_dispatch]
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- run: unzip -o '.zip'
- uses: actions/setup-java@v4
with:
distribution: temurin
java-version: '17'
- uses: gradle/actions/setup-gradle@v3
with:
gradle-version: '8.1.1'
- run: gradle build --no-daemon
working-directory: AstralRift
- uses: actions/upload-artifact@v4
with:
name: AstralRift-jar
path: AstralRift/build/libs/.jar
